

name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}    
     
    
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo $raw
          echo $branch
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - if: ${{ env.BRANCH == 'main' }}
        run: echo ${{ env.BRANCH }}
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.ACTION_TOKEN }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
